[organization] Add missing required names for users in the sample organization to create
Otherwise, the POST request does not succeed, with the following error:

```
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Instantiation of [simple type, class
 com.cosmotech.organization.domain.OrganizationUser] value failed for JSON property name due to missing (therefore NULL) value for creator parameter name which is a non-nullable type; nested exception is com.fasterxml.jackson.module.k
otlin.MissingKotlinParameterException: Instantiation of [simple type, class com.cosmotech.organization.domain.OrganizationUser] value failed for JSON property name due to missing (therefore NULL) value for creator parameter name which
 is a non-nullable type
```