Make sure logging-interceptor has the same version as OkHttp
Otherwise, we may run into NoSuchMethodError issue
when submitting scenario run requests and
the application logging level is TRACE.

The issue is caused by conflicting versions of Okttp
Logging Interceptor.

For reference, the root cause was:
```
Caused by: java.lang.NoSuchMethodError: 'void okhttp3.internal.platform.Platform.log(int, java.lang.String, java.lang.Throwable)'
        at okhttp3.logging.HttpLoggingInterceptor$Logger.lambda$static$0(HttpLoggingInterceptor.java:112)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:169)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at io.argoproj.workflow.ApiClient.execute(ApiClient.java:926)
        at io.argoproj.workflow.apis.ArchivedWorkflowServiceApi.archivedWorkflowServiceGetArchivedWorkflowWithHttpInfo(ArchivedWorkflowServiceApi.java:267)
        at io.argoproj.workflow.apis.ArchivedWorkflowServiceApi.archivedWorkflowServiceGetArchivedWorkflow(ArchivedWorkflowServiceApi.java:247)
        at com.cosmotech.scenariorun.workflow.argo.ArgoWorkflowService.getActiveWorkflow(ArgoWorkflowService.kt:127)
        at com.cosmotech.scenariorun.workflow.argo.ArgoWorkflowService.getWorkflowStatus(ArgoWorkflowService.kt:102)
        at com.cosmotech.scenariorun.workflow.argo.ArgoWorkflowService.onWorkflowStatusRequest(ArgoWorkflowService.kt:388)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
        ... 141 common frames omitted
```